Separated introduction section of MXD tutorial
eclipse-tractusx/tutorial-resources pull request #95
Opened 2023-10-09 07:57 UTC by jkbquabeck

## Description
 
This PR publishes the first step of the reworked MXD tutorial. This was requested in issue #315 (https://github.com/eclipse-tractusx/eclipse-tractusx.github.io/issues/315). The MXD tutorials are to be published in different repositories, starting with tutorial_resources.

## Pre-review checks

Please ensure to do as many of the following checks as possible, before asking for committer review:

- [ ] DEPENDENCIES are up-to-date. [Dash license tool](https://github.com/eclipse/dash-licenses). Committers can open IP issues for restricted libs.
- [x] [Copyright and license header](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-02) are present on all affected files

2023-10-10 05:41 UTC, paullatzelsperger requested changes

2023-10-10 05:41 UTC, paullatzelsperger commented on mxd/1_MXD_Introduction.md
> +With the Minimum Tractus-X Dataspace, IT departments can set up their own little data space to perform a data exchange between two parties (Bob and Alice in our example). The MXD can be used as a san
```suggestion
With the Minimum Tractus-X Dataspace, IT departments can set up their own data space to perform a data exchange between two parties (Bob and Alice in our example). The MXD can be used as a sandbox for testing.
```

2023-10-10 05:41 UTC, paullatzelsperger commented on mxd/1_MXD_Introduction.md
> +With the Minimum Tractus-X Dataspace, IT departments can set up their own little data space to perform a data exchange between two parties (Bob and Alice in our example). The MXD can be used as a san
```suggestion
With the Minimum Tractus-X Dataspace (MXD), IT departments can set up their own little data space to perform a data exchange between two parties (Bob and Alice in our example). The MXD can be used as a sandbox for testing.
```

2023-10-10 05:41 UTC, paullatzelsperger commented on mxd/1_MXD_Introduction.md
> +For whom is that relevant?
```suggestion
## 0. Intended audience
```

2023-10-10 05:41 UTC, paullatzelsperger commented on mxd/1_MXD_Introduction.md
> +This tutorial is designed for companies that want to perform data exchange in a "real" Catena-X data space infrastructure.
That is not quite true.
```suggestion
This tutorial is designed for developers who want to get their hands dirty, for companies that want to perform data exchange in actual Catena-X data space infrastructure and generally for curious minds who want to explore dataspaces.
```

2023-10-10 05:41 UTC, paullatzelsperger commented on mxd/1_MXD_Introduction.md
> +Who should execute the tutorial?
move to intended audience. And you don't "execute" a tutorial. You "read" it, or fwiw you "do" it.

2023-10-10 05:41 UTC, paullatzelsperger commented on mxd/1_MXD_Introduction.md
> +IT-Employees with the following skills and previous experience:
```suggestion
Required knowledge/skills:
```

2023-10-10 05:41 UTC, paullatzelsperger commented on mxd/1_MXD_Introduction.md
> +- 1 Managed Identity Wallet
explain briefly what these components are. people may not know

2023-10-10 05:41 UTC, paullatzelsperger commented on mxd/1_MXD_Introduction.md
> +In order to run the Minimum Tractus-X Dataspace "MXD" on your local machine, please make sure the following
```suggestion
In order to run the Minimum Tractus-X Dataspace on your local machine, please make sure the following
```

2023-10-16 15:11 UTC, jkbquabeck commented
@paullatzelsperger adapted your suggestions.
in case you have not spoken to @stephanbcbauer: we will require your approval for the contents of this PR, but upload these on the tutorial branch of the github.io repository.
We will update the MXD tutorial here after testing of the updated setup etc. has been concluded. The point is to keep this document lean for everyone just interested in setting up the MXD.

2023-10-23 06:20 UTC, paullatzelsperger approved these changes

2023-10-30 10:06 UTC, merged